version: "3.9"

services:

    mongo:
        image: mongo
        container_name: mongo_db
        ports:
        - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        container_name: mongo-express-db
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

    app:
        build: .
        container_name: api_server
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
        links:
            - mongo
        depends_on:
            - mongo